### ISSUE TITLE
ERROR: lazydata failed for package ‘ggmap2’

### ISSUE THREAD

**Issue by Otoliths** [RS-eco/ggmap2#1]
> devtools::install_github("RS-eco/ggmap2")
Downloading GitHub repo RS-eco/ggmap2@master
✓  checking for file ‘/private/var/folders/1x/5mjvgdgx0m754gnfv6_dyxqm0000gn/T/RtmpCaPumC/remotes3df6ca98601/RS-eco-ggmap2-e2dc00e/DESCRIPTION’ ...
─  preparing ‘ggmap2’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘ggmap2_0.0.1.tar.gz’ (438ms)
   
* installing *source* package ‘ggmap2’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: file ‘largeislands.rda’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package ‘ggmap2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ggmap2’
Error: Failed to install 'ggmap2' from GitHub:
  (converted from warning) installation of package ‘/var/folders/1x/5mjvgdgx0m754gnfv6_dyxqm0000gn/T//RtmpCaPumC/file3df6d9ce362/ggmap2_0.0.1.tar.gz’ had non-zero exit status

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.1

**Comment by RS-eco** [comment]
Thanks for pointing this out. I should have fixed it now. Please let me know if you encounter any further issues or if you have suggestions for improvement of the package.
