### ISSUE TITLE
object 'rc' not found

### ISSUE THREAD

**Issue by Otoliths** [RS-eco/ggmap2#2]
thanks a lot!

> library(ggmap2)
> library(sf)
> getData2(name = "worldclim", res=30, var="tmin")
Error in .worldclim(..., download = download, extent = extent, path = path) : 
  object 'rc' not found
> getData2(name="CMIP5", var="tmin", res=30, rcp=85, model="AC", year=70)
trying URL 'http://biogeo.ucdavis.edu/data/climate/cmip5/10m/ac85tn70.zip'
Content type 'application/zip' length 9652537 bytes (9.2 MB)
==================================================
downloaded 9.2 MB

Error in .local(x, y, ...) : Cannot get an Extent object from argument y

**Comment by RS-eco** [comment]
Thanks, should be fixed now.
